import { Smile, Users, Cat, Coffee, Plane, ClubIcon as Football, Lightbulb } from 'lucide-react'

export const categoryIcons = {
  'Smileys & Emotion': Smile,
  'People & Body': Users,
  'Animals & Nature': Cat,
  'Food & Drink': Coffee,
  'Travel & Places': Plane,
  'Activities': Football,
  'Objects': Lightbulb,
}

export const emojiCategories = {
  'Smileys & Emotion': [
    { emoji: '😀', name: 'grinning face' },
    { emoji: '😃', name: 'grinning face with big eyes' },
    { emoji: '😄', name: 'grinning face with smiling eyes' },
    { emoji: '😁', name: 'beaming face with smiling eyes' },
    { emoji: '😆', name: 'grinning squinting face' },
    { emoji: '😅', name: 'grinning face with sweat' },
    { emoji: '🤣', name: 'rolling on the floor laughing' },
    { emoji: '😂', name: 'face with tears of joy' },
    { emoji: '🙂', name: 'slightly smiling face' },
    { emoji: '🙃', name: 'upside-down face' },
    { emoji: '😉', name: 'winking face' },
    { emoji: '😊', name: 'smiling face with smiling eyes' },
    { emoji: '😇', name: 'smiling face with halo' },
    { emoji: '🥰', name: 'smiling face with hearts' },
    { emoji: '😍', name: 'smiling face with heart eyes' },
    { emoji: '🤩', name: 'starstruck face' },
    { emoji: '😘', name: 'face blowing a kiss' },
    { emoji: '😗', name: 'kissing face' },
    { emoji: '☺️', name: 'smiling face with rosy cheeks' },
    { emoji: '😚', name: 'kissing face with closed eyes' },
    { emoji: '😙', name: 'kissing face with smiling eyes' },
    { emoji: '🥲', name: 'smiling face with tear' },
    { emoji: '😋', name: 'face savoring food' },
    { emoji: '😛', name: 'face with tongue' },
    { emoji: '😜', name: 'winking face with tongue' },
    { emoji: '🤪', name: 'zany face' },
    { emoji: '😝', name: 'squinting face with tongue' },
    { emoji: '🤑', name: 'money-mouth face' },
    { emoji: '🤗', name: 'hugging face' },
    { emoji: '🤭', name: 'face with hand over mouth' },
    { emoji: '🤫', name: 'shushing face' },
    { emoji: '🤔', name: 'thinking face' },
    { emoji: '🤐', name: 'zipper-mouth face' },
    { emoji: '🤨', name: 'face with raised eyebrow' },
    { emoji: '😐', name: 'neutral face' },
    { emoji: '😑', name: 'expressionless face' },
    { emoji: '😶', name: 'face without mouth' },
    { emoji: '😏', name: 'smirking face' },
    { emoji: '😒', name: 'unamused face' },
    { emoji: '🙄', name: 'face rolling eyes' },
    { emoji: '😬', name: 'grimacing face' },
    { emoji: '🤥', name: 'lying face' },
    { emoji: '😌', name: 'relieved face' },
    { emoji: '😔', name: 'pensive face' },
    { emoji: '😪', name: 'sleepy face' },
    { emoji: '🤤', name: 'drooling face' },
    { emoji: '😴', name: 'sleeping face' },
    { emoji: '😷', name: 'face with medical mask' },
    { emoji: '🤒', name: 'face with thermometer' },
    { emoji: '🤕', name: 'face with head-bandage' },
    { emoji: '🤢', name: 'nauseated face' },
    { emoji: '🤮', name: 'vomiting face' },
    { emoji: '🤧', name: 'sneezing face' },
    { emoji: '🥵', name: 'hot face' },
    { emoji: '🥶', name: 'cold face' },
    { emoji: '🥴', name: 'woozy face' },
    { emoji: '😵', name: 'dizzy face' },
    { emoji: '🤯', name: 'exploding head' },
    { emoji: '🤠', name: 'cowboy hat face' },
    { emoji: '🥳', name: 'partying face' },
    { emoji: '🥸', name: 'disguised face' },
    { emoji: '😎', name: 'smiling face with sunglasses' },
    { emoji: '🤓', name: 'nerd face' },
    { emoji: '🧐', name: 'face with monocle' },
    { emoji: '😕', name: 'confused face' },
    { emoji: '😟', name: 'worried face' },
    { emoji: '🙁', name: 'slightly frowning face' },
    { emoji: '☹️', name: 'frowning face' },
    { emoji: '😮', name: 'face in awe' },
    { emoji: '😯', name: 'hushed face' },
    { emoji: '😲', name: 'astonished face' },
    { emoji: '😳', name: 'flushed face' },
    { emoji: '🥺', name: 'pleading face' },
    { emoji: '😦', name: 'frowning face with open mouth' },
    { emoji: '😧', name: 'anguished face' },
    { emoji: '😨', name: 'fearful face' },
    { emoji: '😰', name: 'anxious face with sweat' },
    { emoji: '😥', name: 'sad but relieved face' },
    { emoji: '😢', name: 'crying face' },
    { emoji: '😭', name: 'loudly crying face' },
    { emoji: '😱', name: 'face screaming in fear' },
    { emoji: '😖', name: 'confounded face' },
    { emoji: '😣', name: 'persevering face' },
    { emoji: '😞', name: 'disappointed face' },
    { emoji: '😓', name: 'downcast face with sweat' },
    { emoji: '😩', name: 'weary face' },
    { emoji: '😫', name: 'tired face' },
    { emoji: '🥱', name: 'yawning face' },
    { emoji: '😤', name: 'face with steam from nose' },
    { emoji: '😡', name: 'pouting face' },
    { emoji: '😠', name: 'angry face' },
    { emoji: '🤬', name: 'face with symbols on mouth' },
    { emoji: '😈', name: 'smiling face with horns' },
    { emoji: '👿', name: 'angry face with horns' },
    { emoji: '💀', name: 'skull' },
    { emoji: '☠️', name: 'skull and crossbones' },
    { emoji: '💩', name: 'pile of poo' },
    { emoji: '🤡', name: 'clown face' },
    { emoji: '👹', name: 'ogre' },
    { emoji: '👺', name: 'goblin' },
    { emoji: '👻', name: 'ghost' },
    { emoji: '👽', name: 'alien' },
    { emoji: '👾', name: 'alien monster' },
    { emoji: '🤖', name: 'robot' },
    { emoji: '😺', name: 'grinning cat face' },
    { emoji: '😸', name: 'grinning cat face with smiling eyes' },
    { emoji: '😹', name: 'cat face with tears of joy' },
    { emoji: '😻', name: 'smiling cat face with heart eyes' },
    { emoji: '😼', name: 'cat face with wry smile' },
    { emoji: '😽', name: 'kissing cat face' },
    { emoji: '🙀', name: 'weary cat face' },
    { emoji: '😿', name: 'crying cat face' },
    { emoji: '😾', name: 'pouting cat face' },
    { emoji: '🙈', name: 'see-no-evil monkey' },
    { emoji: '🙉', name: 'hear-no-evil monkey' },
    { emoji: '🙊', name: 'speak-no-evil monkey' }
  ],
  'People & Body': [
    { emoji: '👋', name: 'waving hand' },
    { emoji: '🤚', name: 'raised back of hand' },
    { emoji: '🖐️', name: 'hand with fingers splayed' },
    { emoji: '✋', name: 'raised hand' },
    { emoji: '🖖', name: 'vulcan salute' },
    { emoji: '👌', name: 'OK hand' },
    { emoji: '🤌', name: 'pinched fingers' },
    { emoji: '🤏', name: 'pinching hand' },
    { emoji: '✌️', name: 'victory hand' },
    { emoji: '🤞', name: 'crossed fingers' },
    { emoji: '🤟', name: 'love-you gesture' },
    { emoji: '🤘', name: 'sign of the horns' },
    { emoji: '🤙', name: 'call me hand' },
    { emoji: '👈', name: 'backhand index pointing left' },
    { emoji: '👉', name: 'backhand index pointing right' },
    { emoji: '👆', name: 'backhand index pointing up' },
    { emoji: '🖕', name: 'reversed hand with middle finger extended' },
    { emoji: '👇', name: 'backhand index pointing down' },
    { emoji: '☝️', name: 'index pointing up' },
    { emoji: '👍', name: 'thumbs up' },
    { emoji: '👎', name: 'thumbs down' },
    { emoji: '✊', name: 'raised fist' },
    { emoji: '👊', name: 'oncoming fist' },
    { emoji: '🤛', name: 'left-facing fist' },
    { emoji: '🤜', name: 'right-facing fist' },
    { emoji: '👏', name: 'clapping hands' },
    { emoji: '🙌', name: 'raising hands' },
    { emoji: '👐', name: 'open hands' },
    { emoji: '🤲', name: 'palms up together' },
    { emoji: '🤝', name: 'handshake' },
    { emoji: '🙏', name: 'folded hands' },
    { emoji: '✍️', name: 'writing hand' },
    { emoji: '💅', name: 'nail polish' },
    { emoji: '🤳', name: 'selfie' },
    { emoji: '💪', name: 'flexed biceps' },
    { emoji: '🦾', name: 'mechanical arm' },
    { emoji: '🦿', name: 'mechanical leg' },
    { emoji: '🦵', name: 'leg' },
    { emoji: '🦶', name: 'foot' },
    { emoji: '👂', name: 'ear' },
    { emoji: '🦻', name: 'ear with hearing aid' },
    { emoji: '👃', name: 'nose' },
    { emoji: '🧠', name: 'brain' },
    { emoji: '🫀', name: 'anatomical heart' },
    { emoji: '🫁', name: 'lungs' },
    { emoji: '🦷', name: 'tooth' },
    { emoji: '🦴', name: 'bone' },
    { emoji: '👀', name: 'eyes' },
    { emoji: '👁️', name: 'eye' },
    { emoji: '👅', name: 'tongue' },
    { emoji: '👄', name: 'mouth' },
    { emoji: '👶', name: 'baby' },
    { emoji: '🧒', name: 'child' },
    { emoji: '👦', name: 'boy' },
    { emoji: '👧', name: 'girl' },
    { emoji: '🧑', name: 'person' },
    { emoji: '👱', name: 'person: blond hair' },
    { emoji: '👨', name: 'man' },
    { emoji: '🧔', name: 'person: beard' },
    { emoji: '👩', name: 'woman' },
    { emoji: '🧓', name: 'older adult' },
    { emoji: '👴', name: 'older man' },
    { emoji: '👵', name: 'older woman' },
    { emoji: '🙍', name: 'person frowning' },
    { emoji: '🙎', name: 'person pouting' },
    { emoji: '🙅', name: 'person gesturing no' },
    { emoji: '🙆', name: 'person gesturing OK' },
    { emoji: '💁', name: 'person tipping hand' },
    { emoji: '🙋', name: 'person raising hand' },
    { emoji: '🧏', name: 'deaf person' },
    { emoji: '🙇', name: 'person bowing' },
    { emoji: '🤦', name: 'person facepalming' },
    { emoji: '🤷', name: 'person shrugging' },
    { emoji: '👮', name: 'police officer' },
    { emoji: '🕵️', name: 'detective' },
    { emoji: '💂', name: 'guard' },
    { emoji: '🥷', name: 'ninja' },
    { emoji: '👷', name: 'construction worker' },
    { emoji: '🤴', name: 'prince' },
    { emoji: '👸', name: 'princess' },
    { emoji: '👳', name: 'person: turban' },
    { emoji: '👲', name: 'person: mandarin' },
    { emoji: '🧕', name: 'woman: headscarf' },
    { emoji: '🤵', name: 'man in tuxedo' },
    { emoji: '👰', name: 'bride with veil' },
    { emoji: '🤰', name: 'pregnant woman' },
    { emoji: '🤱', name: 'breast-feeding' },
    { emoji: '👼', name: 'baby angel' },
    { emoji: '🎅', name: 'Santa Claus' },
    { emoji: '🤶', name: 'Mrs. Claus' },
    { emoji: '🦸', name: 'superhero' },
    { emoji: '🦹', name: 'supervillain' },
    { emoji: '🧙', name: 'mage' },
    { emoji: '🧚', name: 'fairy' },
    { emoji: '🧛', name: 'vampire' },
    { emoji: '🧜', name: 'mermaid' },
    { emoji: '🧝', name: 'elf' },
    { emoji: '🧞', name: 'genie' },
    { emoji: '🧟', name: 'zombie' },
    { emoji: '💆', name: 'person getting massage' },
    { emoji: '💇', name: 'person getting haircut' },
    { emoji: '🚶', name: 'person walking' },
    { emoji: '🧍', name: 'person standing' },
    { emoji: '🧎', name: 'person kneeling' },
    { emoji: '🏃', name: 'person running' },
    { emoji: '💃', name: 'woman dancing' },
    { emoji: '🕺', name: 'man dancing' },
    { emoji: '🕴️', name: 'person in suit levitating' },
    { emoji: '👯', name: 'people with bunny ears' },
    { emoji: '🧖', name: 'person in steamy room' },
    { emoji: '🧗', name: 'person climbing' },
    { emoji: '🤺', name: 'person fencing' },
    { emoji: '🏇', name: 'person horse racing' },
    { emoji: '⛷️', name: 'person skiing' },
    { emoji: '🏂', name: 'person snowboarding' },
    { emoji: '🏌️', name: 'person golfing' },
    { emoji: '🏄', name: 'person surfing' },
    { emoji: '🚣', name: 'person rowing boat' },
    { emoji: '🏊', name: 'person swimming' },
    { emoji: '⛹️', name: 'person bouncing ball' },
    { emoji: '🏋️', name: 'person lifting weights' },
    { emoji: '🚴', name: 'person biking' },
    { emoji: '🚵', name: 'person mountain biking' },
    { emoji: '🤸', name: 'person cartwheeling' },
    { emoji: '🤼', name: 'people wrestling' },
    { emoji: '🤽', name: 'person playing water polo' },
    { emoji: '🤾', name: 'person playing handball' },
    { emoji: '🤹', name: 'person juggling' },
    { emoji: '🧘', name: 'person in lotus position' },
    { emoji: '🛀', name: 'person taking bath' },
    { emoji: '🛌', name: 'person in bed' }
  ],
  'Animals & Nature': [
    { emoji: '🐵', name: 'monkey' },
    { emoji: '🐒', name: 'monkey face' },
    { emoji: '🦍', name: 'gorilla' },
    { emoji: '🦧', name: 'orangutan' },
    { emoji: '🐶', name: 'dog face' },
    { emoji: '🐕', name: 'dog' },
    { emoji: '🦮', name: 'guide dog' },
    { emoji: '🐕‍🦺', name: 'service dog' },
    { emoji: '🐩', name: 'poodle' },
    { emoji: '🐺', name: 'wolf' },
    { emoji: '🦊', name: 'fox' },
    { emoji: '🦝', name: 'raccoon' },
    { emoji: '🐱', name: 'cat face' },
    { emoji: '🐈', name: 'cat' },
    { emoji: '🐈‍⬛', name: 'black cat' },
    { emoji: '🦁', name: 'lion' },
    { emoji: '🐯', name: 'tiger' },
    { emoji: '🐅', name: 'tiger face' },
    { emoji: '🐆', name: 'leopard' },
    { emoji: '🐴', name: 'horse face' },
    { emoji: '🐎', name: 'horse' },
    { emoji: '🦄', name: 'unicorn' },
    { emoji: '🦓', name: 'zebra' },
    { emoji: '🦌', name: 'deer' },
    { emoji: '🦬', name: 'bison' },
    { emoji: '🐮', name: 'cow face' },
    { emoji: '🐂', name: 'ox' },
    { emoji: '🐃', name: 'water buffalo' },
    { emoji: '🐄', name: 'cow' },
    { emoji: '🐷', name: 'pig face' },
    { emoji: '🐖', name: 'pig' },
    { emoji: '🐗', name: 'boar' },
    { emoji: '🐽', name: 'pig nose' },
    { emoji: '🐏', name: 'ram' },
    { emoji: '🐑', name: 'ewe' },
    { emoji: '🐐', name: 'goat' },
    { emoji: '🐪', name: 'dromedary camel' },
    { emoji: '🐫', name: 'two-hump camel' },
    { emoji: '🦙', name: 'llama' },
    { emoji: '🦒', name: 'giraffe' },
    { emoji: '🐘', name: 'elephant' },
    { emoji: '🦣', name: 'mammoth' },
    { emoji: '🦏', name: 'rhinoceros' },
    { emoji: '🦛', name: 'hippopotamus' },
    { emoji: '🐭', name: 'mouse face' },
    { emoji: '🐁', name: 'mouse' },
    { emoji: '🐀', name: 'rat' },
    { emoji: '🐹', name: 'hamster' },
    { emoji: '🐰', name: 'rabbit face' },
    { emoji: '🐇', name: 'rabbit' },
    { emoji: '🐿️', name: 'chipmunk' },
    { emoji: '🦫', name: 'beaver' },
    { emoji: '🦔', name: 'hedgehog' },
    { emoji: '🦇', name: 'bat' },
    { emoji: '🐻', name: 'bear' },
    { emoji: '🐻‍❄️', name: 'polar bear' },
    { emoji: '🐨', name: 'koala' },
    { emoji: '🐼', name: 'panda' },
    { emoji: '🦥', name: 'sloth' },
    { emoji: '🦦', name: 'otter' },
    { emoji: '🦨', name: 'skunk' },
    { emoji: '🦘', name: 'kangaroo' },
    { emoji: '🦡', name: 'badger' },
    { emoji: '🐾', name: 'paw prints' },
    { emoji: '🦃', name: 'turkey' },
    { emoji: '🐔', name: 'chicken' },
    { emoji: '🐓', name: 'rooster' },
    { emoji: '🐣', name: 'hatching chick' },
    { emoji: '🐤', name: 'baby chick' },
    { emoji: '🐥', name: 'front-facing baby chick' },
    { emoji: '🐦', name: 'bird' },
    { emoji: '🐧', name: 'penguin' },
    { emoji: '🕊️', name: 'dove' },
    { emoji: '🦅', name: 'eagle' },
    { emoji: '🦆', name: 'duck' },
    { emoji: '🦢', name: 'swan' },
    { emoji: '🦉', name: 'owl' },
    { emoji: '🦤', name: 'dodo' },
    { emoji: '🪶', name: 'feather' },
    { emoji: '🦩', name: 'flamingo' },
    { emoji: '🦚', name: 'peacock' },
    { emoji: '🦜', name: 'parrot' },
    { emoji: '🐸', name: 'frog' },
    { emoji: '🐊', name: 'crocodile' },
    { emoji: '🐢', name: 'turtle' },
    { emoji: '🦎', name: 'lizard' },
    { emoji: '🐍', name: 'snake' },
    { emoji: '🐲', name: 'dragon face' },
    { emoji: '🐉', name: 'dragon' },
    { emoji: '🦕', name: 'sauropod' },
    { emoji: '🦖', name: 'T-Rex' },
    { emoji: '🐳', name: 'spouting whale' },
    { emoji: '🐋', name: 'whale' },
    { emoji: '🐬', name: 'dolphin' },
    { emoji: '🦭', name: 'seal' },
    { emoji: '🐟', name: 'fish' },
    { emoji: '🐠', name: 'tropical fish' },
    { emoji: '🐡', name: 'blowfish' },
    { emoji: '🦈', name: 'shark' },
    { emoji: '🐙', name: 'octopus' },
    { emoji: '🐚', name: 'spiral shell' },
    { emoji: '🐌', name: 'snail' },
    { emoji: '🦋', name: 'butterfly' },
    { emoji: '🐛', name: 'bug' },
    { emoji: '🐜', name: 'ant' },
    { emoji: '🐝', name: 'honeybee' },
    { emoji: '🪲', name: 'beetle' },
    { emoji: '🐞', name: 'lady beetle' },
    { emoji: '🦗', name: 'cricket' },
    { emoji: '🪳', name: 'cockroach' },
    { emoji: '🕷️', name: 'spider' },
    { emoji: '🕸️', name: 'spider web' },
    { emoji: '🦂', name: 'scorpion' },
    { emoji: '🦟', name: 'mosquito' },
    { emoji: '🪰', name: 'fly' },
    { emoji: '🪱', name: 'worm' },
    { emoji: '🦠', name: 'microbe' },
    { emoji: '💐', name: 'bouquet' },
    { emoji: '🌸', name: 'cherry blossom' },
    { emoji: '💮', name: 'white flower' },
    { emoji: '🏵️', name: 'rosette' },
    { emoji: '🌹', name: 'rose' },
    { emoji: '🥀', name: 'wilted rose' },
    { emoji: '🌺', name: 'hibiscus' },
    { emoji: '🌻', name: 'sunflower' },
    { emoji: '🌼', name: 'blossom' },
    { emoji: '🌷', name: 'tulip' },
    { emoji: '🌱', name: 'seedling' },
    { emoji: '🪴', name: 'potted plant' },
    { emoji: '🌲', name: 'evergreen tree' },
    { emoji: '🌳', name: 'deciduous tree' },
    { emoji: '🌴', name: 'palm tree' },
    { emoji: '🌵', name: 'cactus' },
    { emoji: '🌾', name: 'sheaf of rice' },
    { emoji: '🌿', name: 'herb' },
    { emoji: '☘️', name: 'shamrock' },
    { emoji: '🍀', name: 'four leaf clover' },
    { emoji: '🍁', name: 'maple leaf' },
    { emoji: '🍂', name: 'fallen leaf' },
    { emoji: '🍃', name: 'leaf fluttering in wind' }
  ],
  'Food & Drink': [
    { emoji: '🍇', name: 'grapes' },
    { emoji: '🍈', name: 'melon' },
    { emoji: '🍉', name: 'watermelon' },
    { emoji: '🍊', name: 'tangerine' },
    { emoji: '🍋', name: 'lemon' },
    { emoji: '🍌', name: 'banana' },
    { emoji: '🍍', name: 'pineapple' },
    { emoji: '🥭', name: 'mango' },
    { emoji: '🍎', name: 'red apple' },
    { emoji: '🍏', name: 'green apple' },
    { emoji: '🍐', name: 'pear' },
    { emoji: '🍑', name: 'peach' },
    { emoji: '🍒', name: 'cherries' },
    { emoji: '🍓', name: 'strawberry' },
    { emoji: '🫐', name: 'blueberries' },
    { emoji: '🥝', name: 'kiwi fruit' },
    { emoji: '🍅', name: 'tomato' },
    { emoji: '🫒', name: 'olive' },
    { emoji: '🥥', name: 'coconut' },
    { emoji: '🥑', name: 'avocado' },
    { emoji: '🍆', name: 'eggplant' },
    { emoji: '🥔', name: 'potato' },
    { emoji: '🥕', name: 'carrot' },
    { emoji: '🌽', name: 'ear of corn' },
    { emoji: '🌶️', name: 'hot pepper' },
    { emoji: '🫑', name: 'bell pepper' },
    { emoji: '🥒', name: 'cucumber' },
    { emoji: '🥬', name: 'leafy green' },
    { emoji: '🥦', name: 'broccoli' },
    { emoji: '🧄', name: 'garlic' },
    { emoji: '🧅', name: 'onion' },
    { emoji: '🍄', name: 'mushroom' },
    { emoji: '🥜', name: 'peanuts' },
    { emoji: '🌰', name: 'chestnut' },
    { emoji: '🍞', name: 'bread' },
    { emoji: '🥐', name: 'croissant' },
    { emoji: '🥖', name: 'baguette bread' },
    { emoji: '🫓', name: 'flatbread' },
    { emoji: '🥨', name: 'pretzel' },
    { emoji: '🥯', name: 'bagel' },
    { emoji: '🥞', name: 'pancakes' },
    { emoji: '🧇', name: 'waffle' },
    { emoji: '🧀', name: 'cheese wedge' },
    { emoji: '🍖', name: 'meat on bone' },
    { emoji: '🍗', name: 'poultry leg' },
    { emoji: '🥩', name: 'steak' },
    { emoji: '🥓', name: 'bacon' },
    { emoji: '🍔', name: 'hamburger' },
    { emoji: '🍟', name: 'fries' },
    { emoji: '🍕', name: 'pizza' },
    { emoji: '🌭', name: 'hot dog' },
    { emoji: '🥪', name: 'sandwich' },
    { emoji: '🌮', name: 'taco' },
    { emoji: '🌯', name: 'burrito' },
    { emoji: '🫔', name: 'tamale' },
    { emoji: '🥙', name: 'stuffed flatbread' },
    { emoji: '🧆', name: 'falafel' },
    { emoji: '🥚', name: 'egg' },
    { emoji: '🍳', name: 'cooking' },
    { emoji: '🥘', name: 'shallow pan of food' },
    { emoji: '🍲', name: 'pot of food' },
    { emoji: '🫕', name: 'fondue' },
    { emoji: '🥣', name: 'bowl with spoon' },
    { emoji: '🥗', name: 'salad' },
    { emoji: '🍿', name: 'popcorn' },
    { emoji: '🧈', name: 'butter' },
    { emoji: '🧂', name: 'salt' },
    { emoji: '🥫', name: 'canned food' },
    { emoji: '🍱', name: 'bento box' },
    { emoji: '🍘', name: 'rice cracker' },
    { emoji: '🍙', name: 'rice ball' },
    { emoji: '🍚', name: 'cooked rice' },
    { emoji: '🍛', name: 'curry rice' },
    { emoji: '🍜', name: 'steaming bowl' },
    { emoji: '🍝', name: 'spaghetti' },
    { emoji: '🍠', name: 'roasted sweet potato' },
    { emoji: '🍢', name: 'oden' },
    { emoji: '🍣', name: 'sushi' },
    { emoji: '🍤', name: 'fried shrimp' },
    { emoji: '🍥', name: 'fish cake with swirl' },
    { emoji: '🥮', name: 'moon cake' },
    { emoji: '🍡', name: 'dango' },
    { emoji: '🥟', name: 'dumpling' },
    { emoji: '🥠', name: 'fortune cookie' },
    { emoji: '🥡', name: 'takeout box' },
    { emoji: '🦀', name: 'crab' },
    { emoji: '🦞', name: 'lobster' },
    { emoji: '🦐', name: 'shrimp' },
    { emoji: '🦑', name: 'squid' },
    { emoji: '🦪', name: 'oyster' },
    { emoji: '🍦', name: 'ice cream' },
    { emoji: '🍧', name: 'shaved ice' },
    { emoji: '🍨', name: 'ice cream' },
    { emoji: '🍩', name: 'doughnut' },
    { emoji: '🍪', name: 'cookie' },
    { emoji: '🎂', name: 'birthday cake' },
    { emoji: '🍰', name: 'shortcake' },
    { emoji: '🧁', name: 'cupcake' },
    { emoji: '🥧', name: 'pie' },
    { emoji: '🍫', name: 'chocolate bar' },
    { emoji: '🍬', name: 'candy' },
    { emoji: '🍭', name: 'lollipop' },
    { emoji: '🍮', name: 'custard' },
    { emoji: '🍯', name: 'honey pot' },
    { emoji: '🍼', name: 'baby bottle' },
    { emoji: '🥛', name: 'glass of milk' },
    { emoji: '☕', name: 'hot beverage' },
    { emoji: '🫖', name: 'teapot' },
    { emoji: '🍵', name: 'teacup without handle' },
    { emoji: '🍶', name: 'sake bottle' },
    { emoji: '🍾', name: 'bottle with popping cork' },
    { emoji: '🍷', name: 'wine glass' },
    { emoji: '🍸', name: 'cocktail glass' },
    { emoji: '🍹', name: 'tropical drink' },
    { emoji: '🍺', name: 'beer mug' },
    { emoji: '🍻', name: 'clinking beer mugs' },
    { emoji: '🥂', name: 'clinking glasses' },
    { emoji: '🥃', name: 'tumbler glass' },
    { emoji: '🥤', name: 'cup with straw' },
    { emoji: '🧋', name: 'bubble tea' },
    { emoji: '🧃', name: 'beverage box' },
    { emoji: '🧉', name: 'mate' },
    { emoji: '🧊', name: 'ice cube' }
  ],
  'Travel & Places': [
    { emoji: '🚗', name: 'automobile' },
    { emoji: '🚕', name: 'taxi' },
    { emoji: '🚙', name: 'sport utility vehicle' },
    { emoji: '🚌', name: 'bus' },
    { emoji: '🚎', name: 'trolleybus' },
    { emoji: '🏎️', name: 'racingcar' },
    { emoji: '🚓', name:'police car' },
    { emoji: '🚑', name: 'ambulance' },
    { emoji: '🚒', name: 'fire engine' },
    { emoji: '🚐', name: 'minibus' },
    { emoji: '🛻', name: 'pickup truck' },
    { emoji: '🚚', name: 'delivery truck' },
    { emoji: '🚛', name: 'articulated lorry' },
    { emoji: '🚜', name: 'tractor' },
    { emoji: '🦽', name: 'manual wheelchair' },
    { emoji: '🦼', name: 'motorized wheelchair' },
    { emoji: '🛴', name: 'scooter' },
    { emoji: '🚲', name: 'bicycle' },
    { emoji: '🛵', name: 'motor scooter' },
    { emoji: '🏍️', name: 'motorcycle' },
    { emoji: '🛺', name: 'auto rickshaw' },
    { emoji: '🚨', name: 'police car light' },
    { emoji: '🚔', name: 'oncoming police car' },
    { emoji: '🚍', name: 'oncoming bus' },
    { emoji: '🚘', name: 'oncoming automobile' },
    { emoji: '🚖', name: 'oncoming taxi' },
    { emoji: '🚡', name: 'cable car' },
    { emoji: '🚠', name: 'mountain cableway' },
    { emoji: '🚟', name: 'suspension railway' },
    { emoji: '🚃', name: 'railway car' },
    { emoji: '🚋', name: 'tram' },
    { emoji: '🚞', name: 'mountain railway' },
    { emoji: '🚝', name: 'monorail' },
    { emoji: '🚄', name: 'high-speed train' },
    { emoji: '🚅', name: 'bullet train' },
    { emoji: '🚈', name: 'light rail' },
    { emoji: '🚂', name: 'locomotive' },
    { emoji: '🚆', name: 'train' },
    { emoji: '🚇', name: 'metro' },
    { emoji: '🚊', name: 'tram car' },
    { emoji: '🚉', name: 'railway station' },
    { emoji: '✈️', name: 'airplane' },
    { emoji: '🛫', name: 'airplane departure' },
    { emoji: '🛬', name: 'airplane arrival' },
    { emoji: '🛩️', name: 'small airplane' },
    { emoji: '💺', name: 'airplane seat' },
    { emoji: '🛰️', name: 'satellite' },
    { emoji: '🚀', name: 'rocket' },
    { emoji: '🛸', name: 'flying saucer' },
    { emoji: '🚁', name: 'helicopter' },
    { emoji: '🛶', name: 'canoe' },
    { emoji: '⛵', name: 'sailboat' },
    { emoji: '🚤', name: 'speedboat' },
    { emoji: '🛥️', name: 'motor boat' },
    { emoji: '🛳️', name: 'passenger ship' },
    { emoji: '⛴️', name: 'ferry' },
    { emoji: '🚢', name: 'ship' },
    { emoji: '⚓', name: 'anchor' },
    { emoji: '🚧', name: 'construction' },
    { emoji: '⛽', name: 'fuel pump' },
    { emoji: '🚏', name: 'bus stop' },
    { emoji: '🚦', name: 'vertical traffic light' },
    { emoji: '🚥', name: 'traffic light' },
    { emoji: '🗺️', name: 'world map' },
    { emoji: '🗿', name: 'moyai' },
    { emoji: '🗽', name: 'statue of liberty' },
    { emoji: '🗼', name: 'tokyo tower' },
    { emoji: '🏰', name: 'castle' },
    { emoji: '🏯', name: 'japanese castle' },
    { emoji: '🏟️', name: 'stadium' },
    { emoji: '🎡', name: 'ferris wheel' },
    { emoji: '🎢', name: 'roller coaster' },
    { emoji: '🎠', name: 'carousel horse' },
    { emoji: '⛲', name: 'fountain' },
    { emoji: '⛱️', name: 'parasol on ground' },
    { emoji: '🏖️', name: 'beach with umbrella' },
    { emoji: '🏝️', name: 'desert island' },
    { emoji: '🏜️', name: 'desert' },
    { emoji: '🌋', name: 'volcano' },
    { emoji: '⛰️', name: 'mountain' },
    { emoji: '🏔️', name: 'snow-capped mountain' },
    { emoji: '🗻', name: 'mount fuji' },
    { emoji: '🏕️', name: 'camping' },
    { emoji: '⛺', name: 'tent' },
    { emoji: '🏠', name: 'house' },
    { emoji: '🏡', name: 'house with garden' },
    { emoji: '🏘️', name: 'houses' },
    { emoji: '🏚️', name: 'derelict house' },
    { emoji: '🏗️', name: 'building construction' },
    { emoji: '🏭', name: 'factory' },
    { emoji: '🏢', name: 'office building' },
    { emoji: '🏬', name: 'department store' },
    { emoji: '🏣', name: 'post office' },
    { emoji: '🏤', name: 'european post office' },
    { emoji: '🏥', name: 'hospital' },
    { emoji: '🏦', name: 'bank' },
    { emoji: '🏨', name: 'hotel' },
    { emoji: '🏪', name: 'convenience store' },
    { emoji: '🏫', name: 'school' },
    { emoji: '🏩', name: 'love hotel' },
    { emoji: '💒', name: 'wedding' },
    { emoji: '🏛️', name: 'classical building' },
    { emoji: '⛪', name: 'church' },
    { emoji: '🕌', name: 'mosque' },
    { emoji: '🕍', name: 'synagogue' },
    { emoji: '🕋', name: 'kaaba' },
    { emoji: '⛩️', name: 'shinto shrine' },
    { emoji: '🛤️', name: 'railway track' },
    { emoji: '🛣️', name: 'motorway' },
    { emoji: '🗾', name: 'map of japan' },
    { emoji: '🎑', name: 'moon viewing ceremony' },
    { emoji: '🏞️', name: 'national park' },
    { emoji: '🌅', name: 'sunrise' },
    { emoji: '🌄', name: 'sunrise over mountains' },
    { emoji: '🌠', name: 'shooting star' },
    { emoji: '🎇', name: 'firecracker' },
    { emoji: '🎆', name: 'fireworks' },
    { emoji: '🌇', name: 'cityscape at sunset' },
    { emoji: '🌆', name: 'cityscape' },
    { emoji: '🏙️', name: 'cityscape' },
    { emoji: '🌃', name: 'night with stars' },
    { emoji: '🌌', name: 'milky way' },
    { emoji: '🌉', name: 'bridge at night' },
    { emoji: '🌁', name: 'fog' }
  ],
  'Activities': [
    { emoji: '🎃', name: 'jack-o-lantern' },
    { emoji: '🎄', name: 'Christmas tree' },
    { emoji: '🎆', name: 'fireworks' },
    { emoji: '🎇', name: 'firecracker' },
    { emoji: '🧨', name: 'firecracker' },
    { emoji: '✨', name: 'sparkles' },
    { emoji: '🎈', name: 'balloon' },
    { emoji: '🎉', name: 'party popper' },
    { emoji: '🎊', name: 'confetti ball' },
    { emoji: '🎋', name: 'tanabata tree' },
    { emoji: '🎍', name: 'pine decoration' },
    { emoji: '🎎', name: 'japanese dolls' },
    { emoji: '🎏', name: 'carp streamer' },
    { emoji: '🎐', name: 'wind chime' },
    { emoji: '🎑', name: 'moon viewing ceremony' },
    { emoji: '🧧', name: 'red envelope' },
    { emoji: '🎀', name: 'ribbon' },
    { emoji: '🎁', name: 'wrapped gift' },
    { emoji: '🎗️', name: 'reminder ribbon' },
    { emoji: '🎟️', name: 'admission tickets' },
    { emoji: '🎫', name: 'ticket' },
    { emoji: '🎖️', name: 'military medal' },
    { emoji: '🏆', name: 'trophy' },
    { emoji: '🏅', name: 'sports medal' },
    { emoji: '🥇', name: '1st place medal' },
    { emoji: '🥈', name: '2nd place medal' },
    { emoji: '🥉', name: '3rd place medal' },
    { emoji: '⚽', name: 'soccer ball' },
    { emoji: '⚾', name: 'baseball' },
    { emoji: '🥎', name: 'softball' },
    { emoji: '🏀', name: 'basketball' },
    { emoji: '🏐', name: 'volleyball' },
    { emoji: '🏈', name: 'american football' },
    { emoji: '🏉', name: 'rugby football' },
    { emoji: '🎾', name: 'tennis' },
    { emoji: '🥏', name: 'flying disc' },
    { emoji: '🎳', name: 'bowling' },
    { emoji: '🏏', name: 'cricket bat and ball' },
    { emoji: '🏑', name: 'field hockey stick and ball' },
    { emoji: '🏒', name: 'ice hockey stick and puck' },
    { emoji: '🥍', name: 'lacrosse stick and ball' },
    { emoji: '🏓', name: 'ping pong' },
    { emoji: '🏸', name: 'badminton racquet and shuttlecock' },
    { emoji: '🥊', name: 'boxing glove' },
    { emoji: '🥋', name: 'martial arts uniform' },
    { emoji: '🥅', name: 'goal net' },
    { emoji: '⛳', name: 'flag in hole' },
    { emoji: '⛸️', name: 'ice skate' },
    { emoji: '🎣', name: 'fishing pole and fish' },
    { emoji: '🤿', name: 'diving mask' },
    { emoji: '🎽', name: 'running shirt' },
    { emoji: '🎿', name: 'skis' },
    { emoji: '🛷', name: 'sled' },
    { emoji: '🥌', name: 'curling stone' },
    { emoji: '🎯', name: 'direct hit' },
    { emoji: '🪀', name: 'yo-yo' },
    { emoji: '🪁', name: 'kite' },
    { emoji: '🎱', name: '8 ball' },
    { emoji: '🔮', name: 'crystal ball' },
    { emoji: '🪄', name: 'magic wand' },
    { emoji: '🧿', name: 'nazar amulet' },
    { emoji: '🎮', name: 'video game' },
    { emoji: '🕹️', name: 'joystick' },
    { emoji: '🎰', name: 'slot machine' },
    { emoji: '🎲', name: 'game die' },
    { emoji: '🧩', name: 'puzzle piece' },
    { emoji: '🧸', name: 'teddy bear' },
    { emoji: '🪅', name: 'piñata' },
    { emoji: '🪆', name: 'nesting dolls' },
    { emoji: '♠️', name: 'spade suit' },
    { emoji: '♥️', name: 'heart suit' },
    { emoji: '♦️', name: 'diamond suit' },
    { emoji: '♣️', name: 'club suit' },
    { emoji: '♟️', name: 'chess pawn' },
    { emoji: '🃏', name: 'joker' },
    { emoji: '🀄', name: 'mahjong red dragon' },
    { emoji: '🎴', name: 'playing card' }
  ],
  'Objects': [
    { emoji: '🔇', name: 'speaker with cancellation stroke' },
    { emoji: '🔈', name: 'speaker low volume' },
    { emoji: '🔉', name: 'speaker medium volume' },
    { emoji: '🔊', name: 'speaker high volume' },
    { emoji: '📢', name: 'loudspeaker' },
    { emoji: '📣', name: 'megaphone' },
    { emoji: '📯', name: 'postal horn' },
    { emoji: '🔔', name: 'bell' },
    { emoji: '🔕', name: 'bell with cancellation stroke' },
    { emoji: '🎼', name: 'musical score' },
    { emoji: '🎵', name: 'musical note' },
    { emoji: '🎶', name: 'musical notes' },
    { emoji: '🎙️', name: 'studio microphone' },
    { emoji: '🎚️', name: 'level slider' },
    { emoji: '🎛️', name: 'control knobs' },
    { emoji: '🎤', name: 'microphone' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '📻', name: 'radio' },
    { emoji: '🎷', name: 'saxophone' },
    { emoji: '🪗', name: 'accordion' },
    { emoji: '🎸', name: 'guitar' },
    { emoji: '🎹', name: 'musical keyboard' },
    { emoji: '🎺', name: 'trumpet' },
    { emoji: '🎻', name: 'violin' },
    { emoji: '🪕', name: 'banjo' },
    { emoji: '🥁', name: 'drum' },
    { emoji: '🪘', name: 'long drum' },
    { emoji: '📱', name: 'mobile phone' },
    { emoji: '📲', name: 'mobile phone with arrow' },
    { emoji: '☎️', name: 'telephone receiver' },
    { emoji: '📞', name: 'telephone' },
    { emoji: '📟', name: 'pager' },
    { emoji: '📠', name: 'fax machine' },
    { emoji: '🔋', name: 'battery' },
    { emoji: '🔌', name: 'electric plug' },
    { emoji: '💻', name: 'laptop' },
    { emoji: '🖥️', name: 'desktop computer' },
    { emoji: '🖨️', name: 'printer' },
    { emoji: '⌨️', name: 'keyboard' },
    { emoji: '🖱️', name: 'computer mouse' },
    { emoji: '🖲️', name: 'trackball' },
    { emoji: '💽', name: 'minidisc' },
    { emoji: '💾', name: 'floppy disk' },
    { emoji: '💿', name: 'optical disc' },
    { emoji: '📀', name: 'dvd' },
    { emoji: '🧮', name: 'abacus' },
    { emoji: '🎥', name: 'movie camera' },
    { emoji: '🎞️', name: 'film reels' },
    { emoji: '📽️', name: 'film projector' },
    { emoji: '🎬', name: 'clapper board' },
    { emoji: '📺', name: 'television' },
    { emoji: '📷', name: 'camera' },
    { emoji: '📸', name: 'camera with flash' },
    { emoji: '📹', name: 'video camera' },
    { emoji: '📼', name: 'videocassette' },
    { emoji: '🔍', name: 'magnifying glass tilted left' },
    { emoji: '🔎', name: 'magnifying glass tilted right' },
    { emoji: '🕯️', name: 'candle' },
    { emoji: '💡', name: 'light bulb' },
    { emoji: '🔦', name: 'flashlight' },
    { emoji: '🏮', name: 'izakaya lantern' },
    { emoji: '🪔', name: 'diya lamp' },
    { emoji: '📔', name: 'notebook' },
    { emoji: '📕', name: 'closed book' },
    { emoji: '📖', name: 'open book' },
    { emoji: '📗', name: 'green book' },
    { emoji: '📘', name: 'blue book' },
    { emoji: '📙', name: 'orange book' },
    { emoji: '📚', name: 'books' },
    { emoji: '📓', name: 'notebook' },
    { emoji: '📒', name: 'ledger' },
    { emoji: '📃', name: 'page with curl' },
    { emoji: '📜', name: 'scroll' },
    { emoji: '📄', name: 'page facing up' },
    { emoji: '📰', name: 'newspaper' },
    { emoji: '🗞️', name: 'rolled-up newspaper' },
    { emoji: '📑', name: 'bookmark tabs' },
    { emoji: '🔖', name: 'bookmark' },
    { emoji: '🏷️', name: 'label' },
    { emoji: '💰', name: 'money bag' },
    { emoji: '🪙', name: 'coin' },
    { emoji: '💴', name: 'yen banknote' },
    { emoji: '💵', name: 'dollar banknote' },
    { emoji: '💶', name: 'euro banknote' },
    { emoji: '💷', name: 'pound banknote' },
    { emoji: '💸', name: 'money with wings' },
    { emoji: '💳', name: 'credit card' },
    { emoji: '🧾', name: 'receipt' },
    { emoji: '💹', name: 'chart increasing' },
    { emoji: '✉️', name: 'envelope' },
    { emoji: '📧', name: 'e-mail' },
    { emoji: '📨', name: 'incoming envelope' },
    { emoji: '📩', name: 'envelope with arrow' },
    { emoji: '📤', name: 'outbox tray' },
    { emoji: '📥', name: 'inbox tray' },
    { emoji: '📦', name: 'package' },
    { emoji: '📫', name: 'closed mailbox with raised flag' },
    { emoji: '📪', name: 'closed mailbox with lowered flag' },
    { emoji: '📬', name: 'open mailbox with raised flag' },
    { emoji: '📭', name: 'open mailbox with lowered flag' },
    { emoji: '📮', name: 'postbox' },
    { emoji: '🗳️', name: 'ballot box with ballot' },
    { emoji: '✏️', name: 'pencil' },
    { emoji: '✒️', name: 'black nib' },
    { emoji: '🖋️', name: 'fountain pen' },
    { emoji: '🖊️', name: 'pen' },
    { emoji: '🖌️', name: 'paintbrush' },
    { emoji: '🖍️', name: 'crayon' },
    { emoji: '📝', name: 'memo' },
    { emoji: '💼', name: 'briefcase' },
    { emoji: '📁', name: 'file folder' },
    { emoji: '📂', name: 'open file folder' },
    { emoji: '🗂️', name: 'card index dividers' },
    { emoji: '📅', name: 'calendar' },
    { emoji: '📆', name: 'tear-off calendar' },
    { emoji: '🗒️', name: 'spiral notepad' },
    { emoji: '🗓️', name: 'spiral calendar' },
    { emoji: '📇', name: 'card index' },
    { emoji: '📈', name: 'chart increasing with yen' },
    { emoji: '📉', name: 'chart decreasing with yen' },
    { emoji: '📊', name: 'bar chart' },
    { emoji: '📋', name: 'clipboard' },
    { emoji: '📌', name: 'pushpin' },
    { emoji: '📍', name: 'round pushpin' },
    { emoji: '📎', name: 'paperclip' },
    { emoji: '🖇️', name: 'linked paperclips' },
    { emoji: '📏', name: 'straight ruler' },
    { emoji: '📐', name: 'triangular ruler' },
    { emoji: '✂️', name: 'scissors' },
    { emoji: '🗃️', name: 'card file box' },
    { emoji: '🗄️', name: 'file cabinet' },
    { emoji: '🗑️', name: 'wastebasket' },
    { emoji: '🔒', name: 'lock' },
    { emoji: '🔓', name: 'unlocked' },
    { emoji: '🔏', name: 'locked with pen' },
    { emoji: '🔐', name: 'locked with key' },
    { emoji: '🔑', name: 'key' },
    { emoji: '🗝️', name: 'old key' },
    { emoji: '🔨', name: 'hammer' },
    { emoji: '🪓', name: 'axe' },
    { emoji: '⛏️', name: 'pick' },
    { emoji: '⚒️', name: 'hammer and pick' },
    { emoji: '🛠️', name: 'hammer and wrench' },
    { emoji: '🗡️', name: 'dagger' },
    { emoji: '⚔️', name: 'crossed swords' },
    { emoji: '🔫', name: 'water pistol' },
    { emoji: '🪃', name: 'boomerang' },
    { emoji: '🏹', name: 'bow and arrow' },
    { emoji: '🛡️', name: 'shield' },
    { emoji: '🪚', name: 'hand saw' },
    { emoji: '🔧', name: 'wrench' },
    { emoji: '🪛', name: 'screwdriver' },
    { emoji: '🔩', name: 'nut and bolt' },
    { emoji: '⚙️', name: 'gear' }
  ]
}

